### ISSUE TITLE
2FA Probleme

### ISSUE THREAD

**Issue by JDittmerCOM** [poetter-sebastian/SimpleThenticator#8]
Das ganze System basiert von PHPGangsta und das habe ich vorher auch genutzt. Nun habe ich es mit deinem geupdatet, allerdings gibt es nun Probleme mit dem 2FA bei uns.

Es wird zwar ohne Probleme der Code generiert, aber das Einloggen, also überprüfen des Codes macht Probleme.

Ich nutze den Google Authenticator und Bitwarden. Wenn ich den Code über Google Authenticator nutze, klappt es, aber nicht über Bitwarden oder den Microsoft Authenticator z. B., obwohl alle den gleichen Secret Key nutzen, das ganze hat vor dem "Update" noch alles funktioniert.

Bitwarden und Microsoft zeigen z. B. 123456 an und Google 456789. Am Ende funktioniert nur der von Google.
Wie kann es sein, das zwei unterschiedliche Codes gezeigt werden plötzlich?

**Comment by JDittmerCOM** [comment]
Ich korrigiere .. ich habe eben den Secret Key manuell ebenfalls in Google eingegeben und mir fällt auf, das der QR-Code einen anderen Code generiert, als wenn man den Key manuell eingibt.
Wie kann das sein? Dürfte doch gar nicht passieren.

**Comment by JDittmerCOM** [comment]
Das ist der Bereich, der bei mir den QR Code und den Secret Key anzeigt.

```php
$secret = $auth2fa->createSecret();
$qrCodeUrl = $auth2fa->getQRCodeGoogleUrl($secret, PROJECT_NAME.' ('.$_SESSION['accUsername'].')');
$oneCode = $auth2fa->getCode($secret);
```

Der Secret Key wird nur einmal erstellt und nicht mehrfach. Deswegen verwundert mich das ganze.

**Comment by poetter-sebastian** [comment]
Hallo, das liegt daran, dass noch weitere Daten als QR-Code Gespeichert werden, damit Name und Beschreibung mit in einer Authenticator-App mit dabei sind.

Hier ist auch zu sehen, dass die URL sich folgendermaßen zusammensetzt:  
```php
$urlencoded = urlencode('otpauth://totp/' .
            (!is_null($issuer) ? $issuer . ':' : '') . $label .
            '?secret=' . $secret .
            ($this->alg != 'SHA1' ? '&algorithm='.$this->alg : '') .
            (!is_null($issuer) ? '&issuer=' . $issuer : ''));

return "https://api.qrserver.com/v1/create-qr-code/?data=$urlencoded&size={$width}x$height&ecc=$ecc";
```
Mit der Funktion also folgendermaßen: 
https://api.qrserver.com/v1/create-qr-code/?data=otpauth%3A%2F%2Ftotp%2F_Test_%3Fsecret%3D_SECRET_%26algorithm%3DSHA256&size=200x200&ecc=M

Das heißt:
```php
$qrCodeUrl = $auth2fa->getQRCodeGoogleUrl($secret, PROJECT_NAME.' ('.$_SESSION['accUsername'].')');
```
Könnte in meiner Version nun folgendermaßen sein:
```php
$qrCodeUrl = $auth2fa->getQRCodeGoogleUrl($secret, $_SESSION['accUsername'], PROJECT_NAME);
```

Es kann gut sein, dass Bitwarden oder Microsoft Authenticator mit den Parametern nichts anfangen kann, das müsste ich erstmal testen.

GoogleQR-Dokumentation: https://goqr.me/api/doc/create-qr-code/

**Comment by JDittmerCOM** [comment]
Alles klar, bei mir habe ich es temporär wieder auf das vorherige 2FA gewechselt, damit es überhaupt noch funktioniert und es zu keinen Problemen kommt.

Fand bzw. find es eigenartig das es plötzlich nicht mehr korrekt funktioniert.
Aber dann warte ich auf ein eventuelles Update ab.
Sollte es Änderungen geben, kann ich diese bei mir sonst auch noch einmal Testen.

**Comment by poetter-sebastian** [comment]
Hey nochmal, das ist kein Bug meinerseits, sondern das liegt an Bitwarden und Microsoft, weil sie dem https://www.rfc-editor.org/rfc/rfc6238 nicht folgen und nur SHA1 unterstützen.

Damit sollte das wieder funktionieren, weil der Algorithmus (von mir) standardmäßig auf das sichere SHA256 gesetzt wurden ist (gemäß dem RFC6238): 
```php
$auth2fa = new SimpleAuthenticator(6, "SHA1");
```

Es wäre super, wenn du es nochmal damit testen könntest.

**Comment by JDittmerCOM** [comment]
Diese Methode funktioniert, danke für die schnellen Antworten.
